version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      time: "03:00"
      timezone: "America/New_York"

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
      time: "04:00"
      timezone: "America/New_York"

  - package-ecosystem: composer
    directory: /
    schedule:
      interval: daily
      time: "05:00"
      timezone: "America/New_York"
